### ISSUE TITLE
Setting DNS name

### ISSUE THREAD

**Issue by saraswat2385** [yavijava/yavijava-samples#3]
I want to create a vm from a template but want to change DNS Name of actual template. Please share sample code for same.

**Comment by saraswat2385** [comment]
<img width="808" alt="screen shot 2016-06-16 at 4 01 04 pm" src="https://cloud.githubusercontent.com/assets/8149864/16141484/c51b193e-3479-11e6-8052-377bb2a1d61d.png">
Want to change this DNS Name

**Comment by saraswat2385** [comment]
@michaelrice any help for me on this  ???

**Comment by michaelrice** [comment]
I think that comes from the DNS server, but Im not 100% sure. If its coming from the VM you will have to update the VM which would mean using the GuestAuthManager & GuestProcessManager to execute some program in the guest to do it. I used to do those kind of guest customizations using VIX but VMWare says you should stop that and switch to GuestAuthManager & GuestProcessManager and the other Guest operation stuff thats been added to vSphere.
